### ISSUE TITLE
Release 0.1.3 was a breaking change.

### ISSUE THREAD

**Issue by GnomedDev** [Better-Player/espeakng-sys#8]
According to cargo's version of semver, 0.X.Y where Y is incremented should be non-breaking, however it seems that `espeak_ng_Synthesize`'s second argument changed from `u64` to `usize`. The best solution going forward would be to yank 0.1.3 to prevent cargo automatically breaking projects which depend on this library when a `cargo update` is run, then re-release it as `0.2`.

**Comment by TobiasDeBruijn** [comment]
Thanks for catching that! I didn't even know that changed. I've yanked 0.1.3 and re-released as 0.2.0.
I've also taken this chance to bump the edition to 2021.
